blank_issues_enabled: true
contact_links:
  - name: Question or "how do I…?"
    url: https://github.com/markosharknz1/ha-aipai-light/discussions
    about: For usage questions, ideas, and general chat, please use Discussions.
